/**
 * Safety guard for the static county-stats snapshot.
 *
 * The snapshot (`public/data/county-stats-snapshot.json`) is regenerated by an
 * offline sweep of the unindexed, ~16s-p90 bio-siting backend (manually via
 * `npm run build-county-snapshot`, or on a schedule via the
 * `refresh-county-snapshot` GitHub Action). A backend that returns empty/404 for
 * every county — wrong base URL, degraded auth, partial outage — produces an
 * all-empty or truncated snapshot *without throwing*, which would silently
 * overwrite the good committed table. This guard refuses to publish such a
 * degraded snapshot.
 */
import type { CountyCropStat } from './county-analysis';

/** California has 58 counties; the snapshot must cover every one. */
export const EXPECTED_COUNTY_COUNT = 58;

/**
 * Minimum fraction of the previous snapshot's data-bearing counties a new
 * snapshot must retain. A degraded sweep (transient backend errors that the
 * per-resource fetch swallows rather than throws) can record a county that
 * truly has data as an empty `[]` without failing the build. Because the client
 * now seeds empty entries as authoritative "no data" (instant popups), such a
 * collapse must be caught here, at build time, before it ships. A drop below
 * this fraction signals a partial/degraded sweep and refuses the overwrite;
 * normal day-to-day fluctuation stays well above it.
 */
export const MIN_DATA_COVERAGE_RATIO = 0.5;

export type CountySnapshot = Record<string, CountyCropStat[]>;

export interface SnapshotValidation {
  ok: boolean;
  /** Present only when `ok` is false — a human-readable rejection reason. */
  reason?: string;
}

/** Number of counties carrying at least one crop row. */
export function countCountiesWithData(snapshot: CountySnapshot): number {
  return Object.values(snapshot).filter(stats => stats.length > 0).length;
}

/**
 * Serialize a snapshot to its canonical on-disk form: keys sorted by geoid so
 * the output is byte-stable across runs. The generator fills the snapshot from
 * concurrent fetches, so key insertion order is otherwise non-deterministic —
 * without sorting, every scheduled regeneration would reorder keys and produce
 * a spurious diff, defeating the "commit only when the data changed" no-op.
 */
export function serializeCountySnapshot(snapshot: CountySnapshot): string {
  const ordered: CountySnapshot = {};
  for (const geoid of Object.keys(snapshot).sort()) {
    ordered[geoid] = snapshot[geoid];
  }
  return JSON.stringify(ordered);
}

/**
 * Decide whether a freshly built snapshot is safe to publish.
 *
 * Rejects when:
 *  - it covers fewer than {@link EXPECTED_COUNTY_COUNT} counties (truncated sweep), or
 *  - it has zero counties with data while the previous snapshot had some
 *    (a degraded sweep that would wipe real data), or
 *  - its data coverage collapses below {@link MIN_DATA_COVERAGE_RATIO} of the
 *    previous snapshot's (a partial sweep that silently dropped real counties
 *    to empty — which the client would otherwise ship as authoritative "no
 *    data").
 *
 * `prev` is `null` on the first ever build — there is nothing to degrade from,
 * so the regression checks are skipped.
 */
export function validateCountySnapshot(
  next: CountySnapshot,
  prev: CountySnapshot | null,
): SnapshotValidation {
  const countyCount = Object.keys(next).length;
  if (countyCount < EXPECTED_COUNTY_COUNT) {
    return {
      ok: false,
      reason: `snapshot covers ${countyCount} counties, expected at least ${EXPECTED_COUNTY_COUNT}`,
    };
  }

  const nextWithData = countCountiesWithData(next);
  const prevWithData = prev ? countCountiesWithData(prev) : 0;
  if (nextWithData === 0 && prevWithData > 0) {
    return {
      ok: false,
      reason: `snapshot has 0 counties with data but the previous snapshot had ${prevWithData} — refusing to overwrite (likely a partial or failed backend sweep)`,
    };
  }

  if (prevWithData > 0 && nextWithData < prevWithData * MIN_DATA_COVERAGE_RATIO) {
    return {
      ok: false,
      reason: `snapshot data coverage collapsed from ${prevWithData} to ${nextWithData} counties (below ${Math.round(MIN_DATA_COVERAGE_RATIO * 100)}% retention) — refusing to overwrite (likely a partial or degraded backend sweep)`,
    };
  }

  return { ok: true };
}
